[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Optimizer settings
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
hyperliquid = "https://rpc.hyperliquid.xyz/evm"
testnet = "https://rpc.hyperliquid-testnet.xyz/evm"

[fmt]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
